Order history
MAES-Rewards/maes-rewards pull request #26
Opened 2024-03-01 23:39 UTC by ShahirAliGit

Pull request for associated Jira issue

2024-03-02 03:23 UTC, CerebralDatabank requested changes
Got this error when clicking History:
![image](https://github.com/MAES-Rewards/maes-rewards/assets/24465111/f55f40f4-4454-41e1-95f0-eeb7ac8c4af5)
As we discussed, it's a quick fix regarding the −1 multiplication in the code.

2024-03-02 03:23 UTC, CerebralDatabank commented on app/controllers/users_controller.rb
> +        @history << ["Spent", user.id, user.name, reward.id, reward.name, -1 * reward.point_value, s.created_at, s.updated_at]
As we discussed:
In this line, multiplying the point value by −1 creates an invalid value. The minus should just be tacked onto the left when creating the string.

2024-03-02 03:35 UTC, CerebralDatabank approved these changes
LGTM! 👍

2024-03-03 17:51 UTC, annapachecohartman approved these changes
LGTM!

2024-03-03 22:29 UTC, jhbeeber approved these changes
Looks good to me. Just add fixes for the rubocop errors and it should be good to merge.

2024-03-04 01:31 UTC, merged