Aria
MAES-Rewards/maes-rewards pull request #45
Opened 2024-03-31 04:07 UTC by ShahirAliGit

Final aria labels made

2024-03-31 04:19 UTC, jhbeeber approved these changes
LGTM! Crucial for the accessibility of the website. Good job!

2024-03-31 05:16 UTC, CerebralDatabank requested changes
LGTM except for the comment I put, so just fix that and it should be good

2024-03-31 05:16 UTC, CerebralDatabank commented on app/views/users/activityhistory.html.erb
> +    <%= button_tag("Reset", type: 'button', onclick: "window.location.href='#{user_history_activity_path(@user)}';", aria: {label: "Filter Button"}) %>
I don't think this is labelled correctly. (This same error is on other places as well, please make sure you get all of them)

2024-03-31 23:32 UTC, annapachecohartman approved these changes
Looks good to me, only thing is where did the Help button on the nav bar go? 
<img width="908" alt="Screenshot 2024-03-31 at 6 32 27 PM" src="https://github.com/MAES-Rewards/maes-rewards/assets/126839762/f2ea9220-599e-4d6b-a99c-570cff66b174">

2024-03-31 23:40 UTC, merged

2024-04-09 05:09 UTC, CerebralDatabank reviewed
Approved